# Example user secrets - customize and encrypt with sops
# Run: sops -e secrets.yaml

# SSH keys
ssh-private-key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  # Your SSH private key content
  -----END OPENSSH PRIVATE KEY-----

# Development tokens
github-token: "ghp_your_github_personal_access_token"
gitlab-token: "glpat-your_gitlab_token"

# API keys for development
aws-access-key: "AKIA..."
aws-secret-key: "your-aws-secret"

# GPG private key (if not using YubiKey)
gpg-private-key: |
  -----BEGIN PGP PRIVATE KEY BLOCK-----
  # Your GPG private key
  -----END PGP PRIVATE KEY BLOCK-----

# Application-specific secrets
docker-auth: |
  {
    "auths": {
      "registry.company.com": {
        "auth": "base64-encoded-credentials"
      }
    }
  }

# Database credentials (for development)
dev-db-password: "your-dev-database-password"
