{ config, lib, pkgs, ... }:
{
  imports = [
    ./monitors.nix
    ./workspaces.nix
    ./animations.nix
  ];
  
  config = lib.mkIf config.mySystem.desktop.hyprland.config.enable {
    # Create Hyprland configuration directory
    environment.etc."hypr/hyprland.conf".text = ''
      # Hyprland configuration generated by NixOS
      
      # Import monitor configuration
      ${lib.optionalString config.mySystem.desktop.hyprland.config.monitors ''
        source = ~/.config/hypr/monitors.conf
      ''}
      
      # Import workspace configuration  
      ${lib.optionalString config.mySystem.desktop.hyprland.config.workspaces ''
        source = ~/.config/hypr/workspaces.conf
      ''}
      
      # Import animation configuration
      ${lib.optionalString config.mySystem.desktop.hyprland.config.animations ''
        source = ~/.config/hypr/animations.conf
      ''}
      
      # Import keybinds
      ${lib.optionalString config.mySystem.desktop.hyprland.keybinds.enable ''
        source = ~/.config/hypr/keybinds.conf
      ''}
      
      # General configuration
      general {
          gaps_in = 5
          gaps_out = 10
          border_size = 2
          col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
          col.inactive_border = rgba(595959aa)
          layout = dwindle
          allow_tearing = false
      }
      
      # Input configuration
      input {
          kb_layout = us
          kb_variant =
          kb_model =
          kb_options =
          kb_rules =
          
          follow_mouse = 1
          
          touchpad {
              natural_scroll = yes
          }
          
          sensitivity = 0
      }
      
      # Decoration
      decoration {
          rounding = 10
          
          blur {
              enabled = true
              size = 3
              passes = 1
          }
          
          drop_shadow = yes
          shadow_range = 4
          shadow_render_power = 3
          col.shadow = rgba(1a1a1aee)
      }
      
      # Misc
      misc {
          force_default_wallpaper = -1
          disable_hyprland_logo = true
      }
    '';
  };
}
